# BEGIN_COPYRIGHT
# END_COPYRIGHT

"""
Biobank: large scale biomedical computation on OMERO.

Biobank is a framework built upon OMERO that provides compact and
efficient ways to handle the computational aspects of large scale
biomedical studies.
"""

import datetime

# from setuptools import setup
from distutils.core import setup
from distutils.errors import DistutilsSetupError
from distutils.command.build_py import build_py as du_build_py
from distutils.command.sdist import sdist as du_sdist
from distutils.dep_util import newer, newer_group

import build_configuration


CURRENT_YEAR = datetime.datetime.now().year
DESCRIPTION, LONG_DESCRIPTION = __doc__.strip().split("\n", 1)
LONG_DESCRIPTION = LONG_DESCRIPTION.strip()
URL = "http://biobank.sourceforge.net"
# DOWNLOAD_URL = ""
LICENSE = 'GPL'
CLASSIFIERS = [
  "Programming Language :: Python",
  "License :: OSI Approved :: GNU General Public License (GPL)",
  "Operating System :: POSIX :: Linux",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Intended Audience :: Science/Research",
  ]
PLATFORMS = ["Linux"]
try:
  with open("NAME") as f:
    NAME = f.read().strip()
  with open("VERSION") as f:
    VERSION = f.read().strip()
except IOError:
  raise DistutilsSetupError("failed to read name/version info")
AUTHOR_INFO = [
  ("Gianmauro Cuccuru", "gianmauro.cuccuru@crs4.it"),
  ("Simone Leo", "simone.leo@crs4.it"),
  ("Luca Lianas", "luca.lianas@crs4.it"),
  ("Gianluigi Zanetti", "gianluigi.zanetti@crs4.it"),
  ]
MAINTAINER_INFO = [
  ("Simone Leo", "simone.leo@crs4.it"),
  ("Luca Lianas", "luca.lianas@crs4.it"),
  ]
AUTHOR = ", ".join(t[0] for t in AUTHOR_INFO)
AUTHOR_EMAIL = ", ".join("<%s>" % t[1] for t in AUTHOR_INFO)
MAINTAINER = ", ".join(t[0] for t in MAINTAINER_INFO)
MAINTAINER_EMAIL = ", ".join("<%s>" % t[1] for t in MAINTAINER_INFO)


def write_authors(filename="AUTHORS"):
  if not newer(__file__, filename):
    return
  with open(filename, "w") as f:
    f.write("%s is developed by:\n" % NAME)
    for name, email in AUTHOR_INFO:
      f.write(" * %s <%s>\n" % (name, email))
    f.write("and maintained by:\n")
    for name, email in MAINTAINER_INFO:
      f.write(" * %s <%s>\n" % (name, email))


def write_version(filename="bl/vl/version.py"):
  if not newer("VERSION", filename):
    return
  with open(filename, "w") as f:
    f.write("# GENERATED BY setup.py\n")
    f.write("version='%s'\n" % VERSION)


def write_config():
  target = build_configuration.PYTHON_OUT_FN
  if newer_group([__file__, build_configuration.__file__], target):
    build_configuration.main([])


class build_py(du_build_py):
  def run(self):
    write_version()
    write_config()
    du_build_py.run(self)


class sdist(du_sdist):
  def run(self):
    write_authors()
    du_sdist.run(self)


setup(
  name=NAME,
  description=DESCRIPTION,
  long_description=LONG_DESCRIPTION,
  url=URL,
  ## download_url=DOWNLOAD_URL,
  license=LICENSE,
  classifiers=CLASSIFIERS,
  author=AUTHOR,
  author_email=AUTHOR_EMAIL,
  maintainer=MAINTAINER,
  maintainer_email=MAINTAINER_EMAIL,
  platforms=PLATFORMS,
  version=VERSION,
  packages=[
    'bl',
    'bl.vl',
    'bl.vl.utils',
    'bl.vl.kb',
    'bl.vl.kb.drivers',
    'bl.vl.kb.drivers.omero',
    'bl.vl.serialize',
    'bl.vl.individual',
    'bl.vl.genotype',
    'bl.vl.graph',
    'bl.vl.graph.drivers',
    'bl.vl.app',
    'bl.vl.app.importer',
    'bl.vl.app.kb_query',
    'bl.vl.app.snp_manager',
    'bl.vl.app.workflow_wrapper',
    ],
  cmdclass={
      "sdist": sdist,
      "build_py": build_py
  },
  requires=[
    'omero',
    'pygraph (>=1.8.0)',
    'numpy',
    'pika (==0.9.12)',
    'voluptuous (>=0.7.1)',
    'bulbs (>=0.3)',
  ],
)
