#!/usr/bin/env python

import sys, os
import omero
from bl.vl.kb.drivers.omero.genotyping import GenotypingAdapter as GA


def get_ome_env():
  ome_env = {}
  for var in 'OME_HOST', 'OME_USER', 'OME_PASSWD':
    try:
      ome_env[var] = os.environ[var]
    except KeyError:
      raise ValueError("%s env var not set" % var)
  return ome_env


def get_mdef_tables(ome_env, table_name):
  c = None
  try:
    c = omero.client(ome_env['OME_HOST'])
    s = c.createSession(ome_env['OME_USER'], ome_env['OME_PASSWD'])
    qs = s.getQueryService()
    res = qs.findAllByString('OriginalFile', 'name', table_name, True, None)
  finally:
    if c is not None:
      c.closeSession()
  return res


def main():
  ome_env = get_ome_env()
  print "checking '%s'" % (ome_env['OME_HOST'])
  table_name = GA.SNP_MARKER_DEFINITIONS_TABLE
  mdef_tables = get_mdef_tables(ome_env, table_name)
  print "found %d instances of '%s'" % (len(mdef_tables), table_name)
  if len(mdef_tables) < 1:
    return 1
  return 0


if __name__ == "__main__":
  sys.exit(main())
