import argparse, sys, os

import omero
import omero_ServerErrors_ice

CONFIG_VALUES = {'omero.biobank.neo4j.uri' : 'NEO4J_URI'}

def make_parser():
    parser = argparse.ArgumentParser('Build bl-vl config file')
    parser.add_argument('-H', '--host', type=str, help='omero hostname',
                        required=True)
    parser.add_argument('-U', '--user', type=str, help='omero user',
                        required=True)
    parser.add_argument('-P', '--passwd', type=str, help='omero password',
                        required=True)
    return parser

def get_ome_var(session, ome_var):
    v = session.getConfigService().getConfigValue(ome_var)
    if not v or v == '':
        raise ValueError('%s is not a known config value, please check your server configuration' % ome_var)
    else:
        return v

def dump_conf_values(output_file, config_values):
    output_file.write('# GENERATED BY build_configuration.py\n')
    for k, v in config_values.iteritems():
        output_file.write('%s="%s"\n' % (k, v))

def main(argv):
    parser = make_parser()
    args = parser.parse_args(argv)

    c = omero.client(args.host)

    try:
        s = c.createSession(args.user, args.passwd)
        config = {}
        for ome_val, py_val in CONFIG_VALUES.iteritems():
            config[py_val] = get_ome_var(s, ome_val)
        with open('../bl/vl/kb/config.py', 'w') as ofile:
            dump_conf_values(ofile, config)
    except omero.SecurityViolation, sv:
        print 'ERROR: unable to build configuration file, the specified account does not belong to your OMERO.biobank SYSTEM users'
    except Exception, e:
        print 'ERROR: Unable to build configuration file'
        print e
    finally:
        c.closeSession()
            

if __name__ == '__main__':
    main(sys.argv[1:])
