#!/usr/bin/env python
import sys, os

import argparse
import sys

import csv

"""

Chipal Utility
===============


The purpose of this utility is to simplify exchange of information
between VL and the chipal programs suite.



  bash$ chipal -H biobank05 extract --data-collection foobar --preferred-data-protocol hdfs --fields gender_check
  bash$ chipal -H biobank05 extract --data-collection foobar --preferred-data-protocol hdfs --fields genotype_call

"""


#---------------------------------------------------------------
import logging, time
LOG_FILENAME = 'chipal.log'
logging.basicConfig(filename=LOG_FILENAME,
                    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
                    level=logging.INFO)

logger = logging.getLogger()

ch = logging.StreamHandler()
ch.setLevel(logging.INFO)

formatter = logging.Formatter(fmt='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

ch.setFormatter(formatter)

logger.addHandler(ch)

#---------------------------------------------------------------
import bl.vl.app.chipal.extract


class App(object):
  def __init__(self):
    self.supported_submodules = []
    bl.vl.app.chipal.extract.do_register(self.supported_submodules)

  def make_parser(self):
    parser = argparse.ArgumentParser(description="A magic chipal")
    parser.add_argument('-o', '--ofile', type=argparse.FileType('w'),
                        help='the output tsv file',
                        default=sys.stdout)
    parser.add_argument('-H', '--host', type=str,
                        help='omero host system',
                        default='localhost')
    parser.add_argument('-U', '--user', type=str,
                        help='omero user',
                        default='root')
    parser.add_argument('-P', '--passwd', type=str,
                        help='omero user passwd')
    parser.add_argument('-K', '--keep-tokens', type=int,
                        default=1, help='omero tokens for open session')

    subparsers = parser.add_subparsers()

    for k, h, addp, impl in self.supported_submodules:
      subparser = subparsers.add_parser(k, help=h)
      addp(subparser)
      subparser.set_defaults(func=impl)
    self.parser = parser
    return parser

def main(argv):
  app = App()
  parser = app.make_parser()
  args = parser.parse_args()
  try:
    args.func(args)
  except ValueError, e:
    logger.critical('ValueError exception %s' % e)
    sys.exit(1)

if __name__ == "__main__":
    main(sys.argv)


# Local Variables: **
# mode: python **
# End: **
