#!/usr/bin/env python

# BEGIN_COPYRIGHT
# END_COPYRIGHT

"""
Create global OMERO tables
==========================

Global tables are not related to any specific KB object.
"""

import os, argparse
from bl.vl.kb.drivers.omero.proxy import Proxy


OME_HOST = os.getenv("OME_HOST", "localhost")
OME_USER = os.getenv("OME_USER", "root")
OME_PASSWD = os.getenv("OME_PASSWD", "romeo")


def make_parser():
  parser = argparse.ArgumentParser(
    description=__doc__.lstrip().splitlines()[0],
    formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
  parser.add_argument('-H', '--host', metavar="STRING",
                      help='OMERO hostname', default=OME_HOST)
  parser.add_argument('-U', '--user', metavar="STRING",
                      help='OMERO user', default=OME_USER)
  parser.add_argument('-P', '--passwd', metavar="STRING",
                      help='OMERO password', default=OME_PASSWD)
  parser.add_argument('-d', '--destructive', action='store_true',
                      help='destroy existing tables if present')
  return parser


def main():
  parser = make_parser()
  args = parser.parse_args()
  p = Proxy(args.host, args.user, args.passwd)
  print 'creating global tables in %s' % args.host
  p.create_global_tables(destructive=args.destructive)


if __name__ == "__main__":
  main()
