#!/usr/bin/env python

# BEGIN_COPYRIGHT
# END_COPYRIGHT

#!/usr/bin/env python
import sys
from bl.vl.app.kb_query.main import main

if __name__ == "__main__":
  main(sys.argv[1:])

# Local Variables: **
# mode: python **
# End: **
