#!/usr/bin/env python

# BEGIN_COPYRIGHT
# END_COPYRIGHT


import sys
from bl.vl.app.snp_reannotator.main import main

if __name__ == "__main__":
  main(sys.argv[1:])

# Local Variables: **
# mode: python **
# End: **
